# Generated by Django 2.2.4 on 2019-08-27 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGamePOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('mean_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('comment', models.CharField(max_length=300)),
                ('video_game_poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoGames.VideoGamePOI')),
            ],
        ),
    ]
